# Generated by Django 3.2.10 on 2021-12-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=50, unique=True)),
                ('pertenencia', models.BooleanField(default=False)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_catalogos.paises')),
            ],
        ),
    ]
